-- Tabellen voor Futureproof met AI Dagboekje

CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email TEXT DEFAULT 'daan@student.hu.nl',
  date DATE NOT NULL,
  mood INTEGER DEFAULT 0,
  yesterday_done TEXT DEFAULT '',
  yesterday_learned TEXT DEFAULT '',
  today_planned TEXT DEFAULT '',
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_email, date)
);

-- Activeer Row Level Security (RLS)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.entries ENABLE ROW LEVEL SECURITY;

-- Publieke lees- en schrijfrechten voor client met publishable key
DROP POLICY IF EXISTS "Publiek kan entries lezen" ON public.entries;
CREATE POLICY "Publiek kan entries lezen" ON public.entries
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Publiek kan entries invoegen" ON public.entries;
CREATE POLICY "Publiek kan entries invoegen" ON public.entries
  FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Publiek kan entries bijwerken" ON public.entries;
CREATE POLICY "Publiek kan entries bijwerken" ON public.entries
  FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Publiek kan users lezen" ON public.users;
CREATE POLICY "Publiek kan users lezen" ON public.users
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Publiek kan users aanmaken" ON public.users;
CREATE POLICY "Publiek kan users aanmaken" ON public.users
  FOR INSERT WITH CHECK (true);

-- Seed voorbeeldrijen
INSERT INTO public.users (email, name)
VALUES ('daan@student.hu.nl', 'Daan Hessen')
ON CONFLICT (email) DO NOTHING;

INSERT INTO public.entries (user_email, date, mood, yesterday_done, yesterday_learned, today_planned)
VALUES 
  ('daan@student.hu.nl', CURRENT_DATE - INTERVAL '2 day', 4, 'Kick-off minor Futureproof met AI bijgewoond', 'Prompt engineering en vibecoding concepten', 'Installatie van AI development tools'),
  ('daan@student.hu.nl', CURRENT_DATE - INTERVAL '1 day', 5, 'Basisopzet dagboek gebouwd met SQLite en vanilla JS', 'Node 22 node:sqlite ingebouwde database', 'Supabase integratie toevoegen'),
  ('daan@student.hu.nl', CURRENT_DATE, 5, 'Supabase cloud database gekoppeld en Vercel deployment geoptimaliseerd', 'Supabase GitHub integratie en RLS policies', 'Reflectievragen invullen')
ON CONFLICT (user_email, date) DO NOTHING;
